export const TRADE_TYPE = ['Buy', 'Sell', 'Extra'];
export const TRANSACTION_STATUS = {
  0: 'Preview',
  1: 'Requested',
  2: 'Submitted',
  3: 'PendingAmlScreening',
  4: 'PendingAuthorization',
  5: 'Queued',
  6: 'PendingSignature',
  7: 'Pending3RdPartyManualApproval',
  8: 'Completed',
  9: 'Broadcasting',
  10: 'Confirming',
  11: 'Pending3RdParty',
  12: 'Cancelling',
  13: 'Cancelled',
  14: 'Blocked',
  15: 'Rejected',
  16: 'Failed',
  101: 'Approved',
  102: 'ChangedOwner',
  103: 'Deleted',
  104: 'InTransfer',
  105: 'Locked',
  106: 'NotReadyTransfer',
  107: 'ReadyTransfer',
  108: 'Transferred',
  109: 'TransferredBack',
  110: 'Unlocked',
  1000: 'Unknown'
}