import { ThemeVariables } from '../../@types/theme';

export default function ({}: ThemeVariables) {
  return {
    logo: require('./assets/images/logo.png'),
    spalsh: {
      bg: require('./assets/images/splash_bg.png'),
    },
    onboarding: {
      bg: require('./assets/images/onboarding/bg.png'),
      first: require('./assets/images/onboarding/1.png'),
      second: require('./assets/images/onboarding/2.png'),
      third: require('./assets/images/onboarding/3.png'),
    },
    main: {
      zerooneLogo: require('./assets/images/zeroone-logo.png'),
      zerooneCal: require('./assets/images/zeroone_cal.png'),
      summaryCardBackground: require('./assets/images/summary_card_background.png'),
      bigCoinWithShadow: require('./assets/images/big-coin.png'),
      neww: require('./assets/images/neww.png'),
      zonenew: require('./assets/images/zonenew.png'),
    },
    icons: {
      deposit: require('./assets/images/icons/deposit.png'),
      fiat: require('./assets/images/icons/fiat.png'),
      fiatAlt: require('./assets/images/icons/fiat-alt.png'),
      withdraw: require('./assets/images/icons/withdraw.png'),
      withdrawAlt: require('./assets/images/icons/withdraw-alt.png'),
      transfer: require('./assets/images/icons/transfer.png'),
      zerooneToken: require('./assets/images/icons/zeroone-token.png'),
      returns: require('./assets/images/icons/returns.png'),
    },
    coins: {
      BTC: require('./assets/images/icons/coins/btc.png'),
      BTC_TEST: require('./assets/images/icons/coins/btc.png'),
      CFXQ: require('./assets/images/icons/coins/cfxq.png'),
      DASH: require('./assets/images/icons/coins/dash.png'),
      DBA: require('./assets/images/icons/coins/dba.png'),
      ETH: require('./assets/images/icons/coins/eth.png'),
      ETH_TEST: require('./assets/images/icons/coins/eth.png'),

      // USDT_BSC: require('./assets/images/icons/coins/usdt.png'),
      // USDT_TRON: require('./assets/images/icons/coins/usdt.png'),
      USDT: require('./assets/images/icons/coins/usdt.png'),
      ZONE: require('./assets/images/icons/coins/zone.png'),
      BNB_BSC: require('./assets/images/icons/coins/bnb.png'),
      BNB_TEST: require('./assets/images/icons/coins/bnb.png'),
      XLM: require('./assets/images/icons/coins/xlm.png'),
      XLM_TEST: require('./assets/images/icons/coins/xlm.png'),

      LTC: require('./assets/images/icons/coins/ltc.png'),
      LTC_TEST: require('./assets/images/icons/coins/ltc.png'),
      BAT: require('./assets/images/icons/coins/bat.png'),
      XRP: require('./assets/images/icons/coins/xrp.png'),
      SHIB: require('./assets/images/icons/coins/shib.png'),
      SHIB_BSC: require('./assets/images/icons/coins/shib.png'),
      TRX: require('./assets/images/icons/coins/trx.png'),
      UNI: require('./assets/images/icons/coins/uni.png'),
      USDC: require('./assets/images/icons/coins/usdc.png'),
      ZRX: require('./assets/images/icons/coins/zrx.png'),
      VAFFA: require('./assets/images/icons/coins/vaffa.png'),
      GEN: require('./assets/images/icons/coins/generic.png'),
    },

    coins1: {
      BTC_TEST: require('./assets/images/icons/coins/btc.png'),
      CFXQ: require('./assets/images/icons/coins/cfxq.png'),
      DASH: require('./assets/images/icons/coins/dash.png'),
      DBA: require('./assets/images/icons/coins/dba.png'),
      ETH_TEST: require('./assets/images/icons/coins/eth.png'),
      // USDT_BSC: require('./assets/images/icons/coins/usdt.png'),
      // USDT_TRON: require('./assets/images/icons/coins/usdt.png'),
      USDT: require('./assets/images/icons/coins/usdt.png'),
      ZONE: require('./assets/images/icons/coins/zone.png'),
      BNB_BSC: require('./assets/images/icons/coins/bnb.png'),
      BNB_TEST: require('./assets/images/icons/coins/bnb.png'),
      XLM_TEST: require('./assets/images/icons/coins/xlm.png'),
      LTC: require('./assets/images/icons/coins/ltc.png'),
      LTC_TEST: require('./assets/images/icons/coins/ltc.png'),
      BAT: require('./assets/images/icons/coins/bat.png'),
      XRP: require('./assets/images/icons/coins/xrp.png'),
      SHIB: require('./assets/images/icons/coins/shib.png'),
      SHIB_BSC: require('./assets/images/icons/coins/shib.png'),
      TRX: require('./assets/images/icons/coins/trx.png'),
      UNI: require('./assets/images/icons/coins/uni.png'),
      USDC: require('./assets/images/icons/coins/usdc.png'),
      ZRX: require('./assets/images/icons/coins/zrx.png'),
      VAFFA: require('./assets/images/icons/coins/vaffa.png'),
      GEN: require('./assets/images/icons/coins/generic.png'),
      AMOY_POLYGON_TEST: require('./assets/images/icons/coins/polygon.png'),
    },
    tab: {
      casa: require('./assets/images/tab/casa.png'),
      conto: require('./assets/images/tab/conto.png'),
      exchange: require('./assets/images/tab/exchange.png'),
      plus: require('./assets/images/tab/plus.png'),
    },
    settings: {
      conto: require('./assets/images/settings/conto.png'),
      cookie: require('./assets/images/settings/cookie.png'),
      financial: require('./assets/images/settings/financial.png'),
      help_support: require('./assets/images/settings/help_support.png'),
      impostazioin: require('./assets/images/settings/impostazioni.png'),
      privacy: require('./assets/images/settings/privacy.png'),
      risk: require('./assets/images/settings/risk.png'),
      sicurezza: require('./assets/images/settings/sicurezza.png'),
      wallet: require('./assets/images/settings/wallet.png'),
    },
    noRecord: require('./assets/images/no-record.png'),
  };
}
